import pickle


# Pour kmeans :
dico_dim2 = {
    0: "Problèmes respiratoires et toux",
    1: "Problèmes de lactation et d'allaitement",
    2: "Activités aquatiques et baignade pour les bébés",
    3: "Hydratation et gestion de la soif chez les bébés",
    4: "Suivi et conseils de lactation",
    5: "Éruptions cutanées et boutons chez les bébés",
    6: "Chutes et blessures légères",
    7: "Constipation et gestion des selles chez les bébés",
    8: "Introduction des aliments solides et des yaourts",
    9: "Dentition et douleur dentaire",
    10: "Protection solaire et accessoires pour l'exposition au soleil",
    11: "Suivi et questionnaires de sommeil",
    12: "Sommeil et routines de sieste",
    13: "Endormissement autonome et gestion des réveils nocturnes",
    14: "Salutations et communications informelles",
    15: "Alimentation et quantité de lait pour les bébés",
    16: "Soins du cuir chevelu et traitements pour les croûtes",
    17: "Problèmes de selles chez les bébés",
    18: "Consommation d'alcool pendant l'allaitement",
    19: "Vaccins et médicaments pour les bébés",
    20: "Conservation et congélation des aliments pour bébés",
    21: "Soins du cordon ombilical",
    22: "Diversification alimentaire",
    23: "Formules lactées et intolérances",
    24: "Problèmes oculaires",
    25: "Vomissements et réhydratation",
    26: "Nettoyage des voies respiratoires",
    27: "Éruptions cutanées chez le nourrisson",
    28: "Vêtements et habillage",
    29: "Sevrage et tirage du lait",
    30: "Adaptation du sommeil et horaires de biberon",
    31: "Formules de salutation et communication",
    32: "Comportement et gestion des émotions",
    33: "Sécurité et aménagement du lit",
    34: "Vitamines et suppléments",
    35: "Méthodes d’endormissement et sommeil autonome",
    36: "Problèmes d’allaitement et lactation",
    37: "Régurgitations",
    38: "Développement moteur et retournement",
    39: "Propreté et apprentissage de la propreté",
    40: "Problèmes buccaux",
    41: "Éruptions cutanées et boutons",
    42: "Transition alimentaire et lait",
    43: "Hygiène buccale et développement vocal",
    44: "Contagion et prévention",
    45: "Accord et communication",
    46: "Problèmes liés aux ongles et morsures",
    47: "Réhydratation et vomissements",
    48: "Eau et boissons",
    49: "Fièvre",
    50: "Symptômes respiratoires",
    51: "Constipation et solutions",
    52: "Produits laitiers pour enfant",
    53: "Altitude et effets sur le bébé",
    54: "Remerciements et communications",
    55: "Vaccins et injections",
    56: "Disponibilité et échanges",
    57: "Quantité de lait et biberons",
    58: "Problème à l'oreilles",
    59: "Débit de lait et formules épaissies",
    60: "Problèmes d’allaitement et engorgement",
    61: "Salutations et communication",
    62: "Érythème fessier et soins",
    63: "Selles de bébé et couleur",
    64: "Risques liés à l'ingestion",
    65: "Endormissement et habitudes de sommeil",
    66: "Prise de nouvelles et disponibilité",
    67: "Équipements pour bébé",
    68: "Préparation des aliments pour bébé",
    69: "Confirmation",
    70: "Chaussures et bain pour bébé",
    71: "Séparation et émotions",
    72: "Fièvre chez l’enfant",
    73: "Accords et confirmations",
}

dico_dim10 = {
    0: "Toux et Symptômes Respiratoires",
    1: "Sommeil et Endormissement",
    2: "Problèmes Buccaux (Aphtes, Muguet)",
    3: "Alimentation et Quantités de Lait/Biberons",
    4: "Comportement, Colères et Propreté",
    5: "Disponibilité et Communication avec Professionnels",
    6: "Vomissements et Réhydratation",
    7: "Lait et Intolérances Alimentaires",
    8: "Diversification Alimentaire",
    9: "Habillage et Températures",
    10: "Constipation et Selles",
    11: "Problèmes de Seins et Allaitement",
    12: "Problèmes de Peau (Boutons, Éruptions)",
    13: "Salutations et Correspondance",
    14: "Affections oculaires",
    15: "Toux Persistante",
    16: "Maladies Contagieuses et Vaccination",
    17: "Régression de Sommeil et Réveil Nocturne",
    18: "Transition Alimentaire (Lait)",
    19: "Vomissements et Diarrhée",
    20: "Fièvre et Traitement",
    21: "Salutations Personnelles",
    22: "Correspondance Sans Thème Spécifique",
    23: "Blessures et Chocs",
    24: "Constipation et Selles",
    25: "Prendre des Nouvelles",
    26: "Salutations et Excuses",
    27: "Problèmes Cutanés (Croûtes, Sécheresse)",
    28: "Disponibilité et Coordination",
    29: "Motricité et Posture",
    30: "Alimentation et Problèmes Digestifs",
    31: "Allaitement et Lactation",
    32: "Dentition et Gencives",
    33: "Loisirs et Protection Solaire",
    34: "Conservation des Aliments",
    35: "Correspondance Générale",
    36: "Alimentation Complémentaire",
    37: "Alcool et Allaitement",
    38: "Correspondance Administrative",
    39: "Problèmes Cutanés (Acné, Piqûres)",
    40: "Ongles et Piqûres d’Insectes",
    41: "Sommeil des bébés et accessoires liés au couchage",
    42: "Hygiène bucco-dentaire pour les enfants",
    43: "Alimentation pour bébés et enfants (laitages et goûters)",
    44: "Questionnaires et accompagnement parental",
    45: "Comportements émotionnels des enfants (colère, frustration)",
    46: "Expressions de gratitude et de bienveillance dans les échanges",
    47: "Accords et formalités légales ou administratives",
    48: "Hydratation des bébés et choix de l’eau",
    49: "Hygiène nasale des bébés",
    50: "Problèmes liés aux selles des bébés",
    51: "Fièvre et soins médicaux des enfants",
    52: "Allaitement et gestion de la succion chez les bébés",
    53: "Quantité de biberons et alimentation des bébés",
    54: "Hoquet chez les bébés",
    55: "Problèmes administratifs ou formels dans les échanges",
    56: "Voyages et altitude pour les bébés",
    57: "Problèmes de peau et irritations chez les bébés (érythème fessier, mycoses)",
    58: "Suppléments et vitamines pour bébés",
    59: "Soins du cordon ombilical",
}

# Pour hdbscan :
dico_dim50_eps02_min200 = {
    0: "Salutations",
    1: "Problèmes oculaires (conjonctivite, sérum, etc.)",
    2: "Hoquet",
    3: "Hygiène dentaire (brossage, dentifrice, etc.)",
    4: "Vaccination (effet secondaire, etc.)",
    5: "Compatibilité allaitement (alcool, médicament, etc.)",
    6: "Contagion et prévention de maladies infectieuses (varicelle, covid, etc.)",
    7: "Préoccupations",
    8: "Suivi (prise de nouvelles etc.)",
    9: "Questions sur les analyses médicales",
    10: "Vaccinations et rappels ",
    11: "Hydratation àl'eau pour les bébé",
    12: "Eau, types d'eau pour le bébé",
    13: "Soins du cordon ombilical",
    14: "Sommeil des jumeaux et problèmes associés",
    15: "Risques liés à l'ingestion (object, Alliments douteux etc.)",
    16: "Remerciements",
    17: "Remerciements",
    18: "Remerciements",
    19: "Suivi (prise de nouvelles etc.)",
    20: "Suivi (prise de nouvelles etc.)",
    21: "Suivi (prise de nouvelles etc.)",
    22: "Informations et suivi après traitement",
    23: "Remplissage de questionnaires",
    24: "Questions diverses",
    25: "Questions diverses",
    26: "Problèmes de gencives et dents",
    27: "Problèmes de gencives et dents",
    28: "Problèmes buccaux (Muguet,rougeur etc.)",
    29: "Chutes et blessures",
    30: "Piqûres, boutons, gonflement (boule)",
    31: "Chutes et blessures",
    32: "Soins des ongles et orteils",  # nom pas fou, en général petit bobo sur les mains et les pieds mais parfois gros bobo alors bon on peut pas mettre petit quand meme
    33: "Boutons et rougeurs",
    34: "Problèmes sur la zone génital",
    35: "Croûte de lait et problème de peau",
    36: "Symptômes respiratoires",
    37: "Rougeurs fessier/génital",
    38: "Érythème et boutons zone du siège",
    39: "Allergies alimentaires (réaction, rougeur, etc.)",
    40: "Réactions allergiques",
    41: "Problèmes d'oreilles (otites etc.)",
    42: "Problèmes d'oreilles (otites etc.)",
    43: "Éruptions cutanées et plaques rouges",
    44: "Éruptions cutanées et plaques rouges",
    45: "Éruptions cutanées et boutons",
    46: "Éruptions cutanées et boutons",
    47: "Éruptions cutanées et boutons",
    48: "propreté et apprentissage continence",
    49: "Posologie et administration de médicaments et de suppléments",
    50: "Conseil médicaments",
    51: "Problème au nez (saignement etc.)",
    52: "Symptômes respiratoires chez l'enfant",
    53: "Vaccins et fièvre",
    54: "Fièvre",
    55: "Vaccins et effet secondaires (fièvre etc.)",
    56: "Altitude et conséquence",
    57: "Respiration et toux",
    58: "Nettoyage des voies respiratoires",
    59: "Nettoyage des voies respiratoires",
    60: "Sommeil et environnement",
    61: "Respiration et toux",
    62: "Fièvre",
    63: "Tétines et sucettes",
    64: "Propreté et apprentissage continence",
    65: "Pleurs et décharges",
    66: "Chaussures, chaussons pour bébé",
    67: "Bain, baignade et contre indication",
    68: "Bain et routine",
    69: "Bain et baignade pour le bébé",
    70: "Protection solaire",
    71: "Conseil transport (avion, voiture etc.)",
    72: "Sorties avec le bébé",
    73: "Température pour l'enfant",
    74: "Habillage et vêtements",
    75: "Régressions et troubles du sommeil",
    76: "Conservation du lait",
    77: "Congélation et conservation des aliments",
    78: "Sécurité et aménagement du lit",
    79: "Difficultés d'endormissement et siestes",
    80: "Comportement et gestion des émotions (parents et enfant)",
    81: "Langage et mouvements chez l'enfant",  # classe pas folle, mélange de truc : languages et soucis autres mais dure à séparer
    82: "Accessoires pour bébé",
    83: "Motricité et développement moteur",
    84: "Retournement et position du bébé pour le sommeil",
    85: "Retournement et position du bébé pour le sommeil",
    86: "Motricité et développement moteur",
    87: "Difficulté lors de l'allaitement",
    88: "Quantité et fréquence du biberons",
    89: "Céréales pour l'alimentation",
    90: "Coliques et douleurs au ventre",
    91: "Alimentation et reflux",
    92: "Sevrage et biberons",
    93: "Constipation et conseil (Hepar etc;)",
    94: "Transition alimentaire et lait",
    95: "Constipation et selles",
    96: "Yaourts et produits laitiers",
    97: "Choix de laits",
    98: "Préparation repas",
    99: "Préparation repas",
    100: "Selles du bébé (couleur, texture etc.)",
    101: "Vomissements et diarrhées",
    102: "Diversification alimentaire",
    103: "Introduction des aliments solides et morceaux",
    104: "Constipation chez l'enfant",
    105: "Question allaitement (fréquence etc.)",
    106: "Sevrage et biberons",
    107: "Quantités de lait et biberons",
    108: "Problèmes au sein chez la mère (douleur, crevasse etc.)",
    109: "Allaitement et lactation chez la mère",
    110: "Régurgitations (de lait) du bébé",
    111: "Réhydratation et vomissements",
    112: "Selles de l'enfant (couleur, texture etc.)",
}

# For hdbscan with after a hand restructuring :
dico_dim50_eps02_min200_V2 = {
    0: "Salutations",
    1: "Problèmes oculaires (conjonctivite, sérum, etc.)",
    2: "Hoquet",
    3: "Hygiène dentaire (brossage, dentifrice, etc.)",
    4: "Vaccination (effet secondaire, etc.)",
    5: "Compatibilité allaitement (alcool, médicament, etc.)",
    6: "Contagion et prévention de maladies infectieuses (varicelle, covid, etc.)",
    7: "Préoccupations",
    8: "Suivi (prise de nouvelles etc.)",
    9: "Questions sur les analyses médicales",
    10: "Vaccinations et rappels",
    11: "Hydratation à l'eau pour les bébé",
    12: "Eau, types d'eau pour le bébé",
    13: "Soins du cordon ombilical",
    14: "Sommeil des jumeaux et problèmes associés",
    15: "Risques liés à l'ingestion (objet, aliments douteux etc.)",
    16: "Remerciements",
    17: "Remerciements",
    18: "Remerciements",
    19: "Suivi (prise de nouvelles etc.)",
    20: "Suivi (prise de nouvelles etc.)",
    21: "Suivi (prise de nouvelles etc.)",
    22: "Informations et suivi après traitement",
    23: "Remplissage de questionnaires",
    24: "Questions diverses",
    25: "Questions diverses",
    26: "Problèmes de gencives et dents",
    27: "Problèmes de gencives et dents",
    28: "Problèmes buccaux (Muguet, rougeur etc.)",
    29: "Chutes et blessures",
    30: "Piqûres, boutons, gonflement (boule)",
    31: "Chutes et blessures",
    32: "Soins des ongles et orteils",
    33: "Boutons et rougeurs",
    34: "Problèmes sur la zone génitale",
    35: "Croûte de lait et problème de peau",
    36: "Symptômes respiratoires",
    37: "Rougeurs fessier/génital",
    38: "Érythème et boutons zone du siège",
    39: "Allergies alimentaires (réaction, rougeur, etc.)",
    40: "Réactions allergiques",
    41: "Problèmes d'oreilles (otites etc.)",
    42: "Problèmes d'oreilles (otites etc.)",
    43: "Éruptions cutanées et plaques rouges",
    44: "Éruptions cutanées et plaques rouges",
    45: "Éruptions cutanées et boutons",
    46: "Éruptions cutanées et boutons",
    47: "Éruptions cutanées et boutons",
    48: "Propreté et apprentissage continence",
    49: "Posologie et administration de médicaments et de suppléments",
    50: "Conseil médicaments",
    51: "Problème au nez (saignement etc.)",
    52: "Symptômes respiratoires chez l'enfant",
    53: "Vaccins et fièvre",
    54: "Fièvre",
    55: "Vaccins et effet secondaires (fièvre etc.)",
    56: "Altitude et conséquence",
    57: "Respiration et toux",
    58: "Nettoyage des voies respiratoires",
    59: "Nettoyage des voies respiratoires",
    60: "Sommeil et environnement",
    61: "Respiration et toux",
    62: "Fièvre",
    63: "Tétines et sucettes",
    64: "Propreté et apprentissage continence",
    65: "Pleurs et décharges",
    66: "Chaussures, chaussons pour bébé",
    67: "Bain, baignade et contre indication",
    68: "Bain et routine",
    69: "Bain et baignade pour le bébé",
    70: "Protection solaire",
    71: "Conseil transport (avion, voiture etc.)",
    72: "Sorties avec le bébé",
    73: "Température pour l'enfant",
    74: "Habillage et vêtements",
    75: "Sommeil et nourriture (biberon, tété etc.)",
    76: "Conservation du lait",
    77: "Congélation et conservation des aliments",
    78: "Sécurité et aménagement du lit",
    79: "Nuit difficile (endormissement compliqué ou réveil tôt)",
    80: "Comportement et gestion des émotions (parents et enfant)",
    81: "Langage et mouvements chez l'enfant",
    82: "Accessoires pour bébé",
    83: "Motricité et développement moteur",
    84: "Retournement et position du bébé pour le sommeil",
    85: "Retournement et position du bébé pour le sommeil",
    86: "Motricité et développement moteur",
    87: "Difficulté lors de l'allaitement",
    88: "Quantité et fréquence du biberon",
    89: "Céréales pour l'alimentation",
    90: "Coliques et douleurs au ventre",
    91: "Alimentation et reflux",
    92: "Sevrage et biberons",
    93: "Constipation et conseil (Hépar, etc;)",
    94: "Transition alimentaire et lait",
    95: "Constipation et selles",
    96: "Yaourts et produits laitiers",
    97: "Choix de laits",
    98: "Préparation repas",
    99: "Préparation repas",
    100: "Selles du bébé (couleur, texture etc.)",
    101: "Vomissements et diarrhées",
    102: "Diversification alimentaire",
    103: "Introduction des aliments solides et morceaux",
    104: "Constipation chez l'enfant",
    105: "Question allaitement (fréquence etc.)",
    106: "Sevrage et biberons",
    107: "Quantités de lait et biberons",
    108: "Problèmes au sein chez la mère (douleur, crevasse etc.)",
    109: "Allaitement et lactation chez la mère",
    110: "Régurgitations (de lait) du bébé",
    111: "Réhydratation et vomissements",
    112: "Selles de l'enfant (couleur, texture etc.)",
    113: "Gestion des émotions et du comportement",
    114: "Difficulté endormissement (pas envie d’être seul etc.)",
    115: "Rituel de sommeil et endormissement autonome",
    116: "Question tétine/pouce pour dormir",
    117: "Rythme de sommeil (réveil tôt, sieste etc.)",
    118: "Question rythme et quantité de sommeil",
    119: "Peur du bébé lors du sommeil et difficulté d’endormissement",
    120: "Difficulté endormissement (angoisse séparation, besoin parent etc.)",
    121: "Sommeil et nourriture",
    122: "Difficulté endormissement et réveil nocturne",
    123: "Question trop dormir, quantité de sommeil",
    124: "Sommeil agité",
    125: "Régression sommeil (réveil nocturne etc.)",
    126: "Question rythme et quantité de sommeil",
    127: "Sommeil allaitement (tété etc.)",
    128: "Réveil nocturne et endormissement au sein/tété/avec parent",
    129: "Question quantité sommeil (trop ou pas assez etc.)",
    130: "Tété / alimentation nocturnes",
    131: "Sommeil et nourriture",
    132: "Sommeil et pleure (pleure de décharge etc.)",
    133: "Sommeil et pleure/crie (cauchemars etc.)",
    134: "Sommeil et tétine/pouce",
    135: "Difficulté pour dormir, s’endormir",
}
# associé aux labels : "../data/nouveau_labels_hdbscan_dim50_eps02_mi200_V2.npy" et aux vecteurs "../data/vec_embeddings_norm_reduit_dim50_neighbors15_mindist005.npy"

with open("dico_tag_cluster_hdbscan_dim50_eps02_min200_V2.pkl", "wb") as f:
    pickle.dump(dico_dim50_eps02_min200_V2, f)
